name: Build for MacOSX

on:
  workflow_run:
    workflows: [Create Release]
    types: [completed]

jobs:
  build:
    name: Build
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          ref: ${{github.ref}}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: |
          export VERSION=$(cat ./version)
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'github.com/aliyun/aliyun-cli/cli.Version=${VERSION}'" -o out/aliyun.amd64 main/main.go
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X 'github.com/aliyun/aliyun-cli/cli.Version=${VERSION}'" -o out/aliyun.arm64 main/main.go
          lipo -output out/aliyun -create out/aliyun.amd64 out/aliyun.arm64
          sh tools/build_pkg.sh ${VERSION}
