name: Build for MacOSX

on:
  workflow_run:
    workflows: [Create Release]
    types: [completed]

jobs:
  build:
    name: Build
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          ref: ${{github.ref}}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'github.com/aliyun/aliyun-cli/cli.Version=${cat ./version}'" -o out/aliyun.amd64 main/main.go
      - run: GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'github.com/aliyun/aliyun-cli/cli.Version=${cat ./version}'" -o out/aliyun.amd64 main/main.go
